version: '3'
services:
  musicnft:
    container_name: 'musicnft'
    image: '${WEBSITE_IMAGE}'
    ports:
      - "3000:3000"
    volumes:
      - musicnft:/client/build/ # build files will be added at this directory !!!

  nginx:
    container_name: 'nginx'
    image: '${NGINX_IMAGE}'
    ports:
      - "80:80"
    volumes:
      - musicnft:/usr/share/nginx/html/musicnft # Copy React App's build files to the Nginx directory

volumes:
  musicnft:
