version: '3'
services:
  musicnft:
    build:
      context: ./client
      dockerfile: Dockerfile
      # newly added
      args:
        - REACT_APP_BACKEND_HOST
      cache_from:
        - '${WEBSITE_IMAGE}'
    image: '${WEBSITE_IMAGE}'
    ports:
      - "3000:3000"
    volumes:
      - musicnft:/client/build/ # build files will be added at this directory !!!

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      cache_from:
        - '${NGINX_IMAGE}'
    image: '${NGINX_IMAGE}'
    ports:
      - "80:80"
    volumes:
      - musicnft:/usr/share/nginx/html/musicnft # Copy React App's build files to the Nginx directory

volumes:
  musicnft:
