version: '3'
services:
  musicnft:
    container_name: musicnft
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - musicnft:./client/build/ # build files will be added at this directory !!!

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - musicnft:/usr/share/nginx/html/musicnft # Copy React App's build files to the Nginx directory

volumes:
  musicnft:
